apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asset-management-ingress
  namespace: asset-management
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: superadmin.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: superadmin-service
            port:
              number: 80
  - host: ams.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ams-service
            port:
              number: 80